apiVersion: v1
kind: Secret
metadata:
  name: zochacha-secrets
  labels:
    app: zochacha
type: Opaque
stringData:
  # MySQL 관련 민감 정보
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: zochacha
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: zochacha
  
  # OAuth 관련 민감 정보
  CLIENT_SECRET: 14nq6ak7c4eajkhc9ghhokg8pvks3jhdrl7hae90p48hkvtjfqob
  
  # .env 파일
  .env: |
    # 데이터베이스 설정
    DB_MODE=mysql
    MYSQL_USER=zochacha
    MYSQL_PASSWORD=password
    MYSQL_HOST=mysql
    MYSQL_PORT=3306
    MYSQL_DB=zochacha

    # OAuth Cognito 관련 설정
    CLIENT_SECRET=14nq6ak7c4eajkhc9ghhokg8pvks3jhdrl7hae90p48hkvtjfqob
    AUTHORIZE_REDIRECT_URL=http://localhost:5000/authorize 